<?xml version="1.0"?>
<package format="3">
  <name>navigation</name>
  <version>0.1.0</version>
  <description>Package for navigation and obstacle avoidance nodes for Mission WindWatch 2024.</description>
  <maintainer email="maintainer@windwatch.com">Your Name</maintainer>
  <license>Apache 2.0</license>

  <!-- Build dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>


  <!-- Execution dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>sensors</depend>

  <!-- Runtime dependencies for ROSIDL -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Declaration that this package is part of the rosidl_interface_packages -->
  <member_of_group>rosidl_interface_packages</member_of_group>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
