/*
Node control_node
Role: Translates the desired trajectory into specific motor commands, implementing control algorithms to follow the planned path accurately.
Subscribed Topics:
/mission/odometry: Current position and orientation of the boat.
/navigation/desired_trajectory: The trajectory generated by the path_planning_node.
Published Topics:
/propulsion/command: High-level propulsion commands (thrust and steering angles) for the motors.
*/

#include "navigation/control_node.hpp"

ControlNode::ControlNode() : Node("control_node")
{
	RCLCPP_INFO(this->get_logger(), "Control Node has started");
}

int main(int argc, char * argv[])
{
    rclcpp::init(argc, argv);
	auto node = std::make_shared<ControlNode>();
    rclcpp::spin(node);
    rclcpp::shutdown();
    return 0;
}
