/*
Node control_node
Role: Translates the desired trajectory into specific motor commands, implementing control algorithms to follow the planned path accurately.
Subscribed Topics:
/mission/odometry: Current position and orientation of the boat.
/navigation/desired_trajectory: The trajectory generated by the path_planning_node.
Published Topics:
/propulsion/command: High-level propulsion commands (thrust and steering angles) for the motors.
*/

// control_node.cpp

#include "navigation/control_node.hpp"
#include <cmath>
#include <algorithm>
#include <boost/math/constants/constants.hpp>

ControlNode::ControlNode()
: Node("control_node"), current_waypoint_index_(0), goal_received_(false),
  prev_error_linear_(0.0), prev_error_angular_(0.0),
  integral_error_linear_(0.0), integral_error_angular_(0.0),
  command_received_(false)
{
    // Souscriptions
    odom_subscription_ = this->create_subscription<nav_msgs::msg::Odometry>(
        "/mission/odometry", 10,
        std::bind(&ControlNode::odomCallback, this, std::placeholders::_1));

    path_subscription_ = this->create_subscription<nav_msgs::msg::Path>(
        "/navigation/desired_trajectory", 10,
        std::bind(&ControlNode::pathCallback, this, std::placeholders::_1));

    // Publication
    cmd_publisher_ = this->create_publisher<geometry_msgs::msg::Twist>(
        "/propulsion/command", 10);

    // Déclaration des paramètres PID et autres
    this->declare_parameter<double>("Kp_linear", 1.0);
    this->declare_parameter<double>("Ki_linear", 0.0);
    this->declare_parameter<double>("Kd_linear", 0.0);
    this->declare_parameter<double>("Kp_angular", 2.0);
    this->declare_parameter<double>("Ki_angular", 0.0);
    this->declare_parameter<double>("Kd_angular", 0.0);
    this->declare_parameter<double>("position_tolerance", 0.5); // mètres
    this->declare_parameter<double>("control_loop_rate", 10.0); // Hz
    this->declare_parameter<double>("timeout_duration", 1.0);   // secondes

    // Récupération des paramètres
    this->get_parameter("Kp_linear", Kp_linear_);
    this->get_parameter("Ki_linear", Ki_linear_);
    this->get_parameter("Kd_linear", Kd_linear_);
    this->get_parameter("Kp_angular", Kp_angular_);
    this->get_parameter("Ki_angular", Ki_angular_);
    this->get_parameter("Kd_angular", Kd_angular_);
    this->get_parameter("position_tolerance", position_tolerance_);
    this->get_parameter("control_loop_rate", control_loop_rate_);
    this->get_parameter("timeout_duration", timeout_duration_);

    // Initialisation du timer pour la boucle de contrôle
    timer_ = this->create_wall_timer(
        std::chrono::milliseconds(static_cast<int>(1000.0 / control_loop_rate_)),
        std::bind(&ControlNode::controlLoop, this));

    // Initialisation du timer de timeout
    timeout_timer_ = this->create_wall_timer(
        std::chrono::milliseconds(static_cast<int>(timeout_duration_ * 1000)),
        std::bind(&ControlNode::checkCommandTimeout, this));

    RCLCPP_INFO(this->get_logger(), "Control Node has started");
}

void ControlNode::odomCallback(const nav_msgs::msg::Odometry::SharedPtr msg)
{
    // Mise à jour de la position et de l'orientation actuelles
    current_pose_ = msg->pose.pose;
    command_received_ = true; // Commande reçue

    if (goal_received_)
    {
        // Les commandes seront traitées dans la boucle de contrôle
    }
}

void ControlNode::pathCallback(const nav_msgs::msg::Path::SharedPtr msg)
{
    // Mise à jour de l'itinéraire
    path_ = msg->poses;
    current_waypoint_index_ = 0;
    goal_received_ = true;
    RCLCPP_INFO(this->get_logger(), "New path received with %zu waypoints", path_.size());
}

void ControlNode::controlLoop()
{
    if (!goal_received_)
    {
        // Aucun objectif à atteindre
        return;
    }

    if (current_waypoint_index_ >= path_.size())
    {
        RCLCPP_INFO(this->get_logger(), "All waypoints reached.");
        goal_received_ = false;
        return;
    }

    // Current waypoint
    auto current_waypoint = path_[current_waypoint_index_].pose;

    // Extraction de la position actuelle
    double x_current = current_pose_.position.x;
    double y_current = current_pose_.position.y;

    // Extraction de l'orientation actuelle (yaw)
    tf2::Quaternion q_current;
    tf2::fromMsg(current_pose_.orientation, q_current);
    double roll_current, pitch_current, yaw_current;
    tf2::Matrix3x3(q_current).getRPY(roll_current, pitch_current, yaw_current);

    // Extraction du point de destination
    double x_goal = current_waypoint.position.x;
    double y_goal = current_waypoint.position.y;

    // Calcul de l'erreur de position
    double error_x = x_goal - x_current;
    double error_y = y_goal - y_current;
    double distance_to_goal = std::sqrt(error_x * error_x + error_y * error_y);

    // Vérification si le waypoint est atteint
    if (distance_to_goal < position_tolerance_)
    {
        RCLCPP_INFO(this->get_logger(), "Waypoint %zu reached.", current_waypoint_index_ + 1);
        current_waypoint_index_++;
        if (current_waypoint_index_ >= path_.size())
        {
            RCLCPP_INFO(this->get_logger(), "Final waypoint reached.");
            goal_received_ = false;
        }
        return;
    }

    // Calcul de l'angle vers le point de destination
    double theta_goal = std::atan2(error_y, error_x);

    // Calcul de l'erreur d'orientation
    double error_theta = theta_goal - yaw_current;
    // Normalisation entre -pi et pi
    error_theta = std::atan2(std::sin(error_theta), std::cos(error_theta));

    // Calcul des erreurs PID
    double error_linear = distance_to_goal;
    double error_angular = error_theta;

    // Intégrales
    integral_error_linear_ += error_linear * (1.0 / control_loop_rate_);
    integral_error_angular_ += error_angular * (1.0 / control_loop_rate_);

    // Dérivées
    double derivative_error_linear = (error_linear - prev_error_linear_) * control_loop_rate_;
    double derivative_error_angular = (error_angular - prev_error_angular_) * control_loop_rate_;

    // PID Calcul
    double linear_speed = Kp_linear_ * error_linear
                         + Ki_linear_ * integral_error_linear_
                         + Kd_linear_ * derivative_error_linear;

    double angular_speed = Kp_angular_ * error_angular
                          + Ki_angular_ * integral_error_angular_
                          + Kd_angular_ * derivative_error_angular;

    // Mise à jour des erreurs précédentes
    prev_error_linear_ = error_linear;
    prev_error_angular_ = error_angular;

    // Limitation des vitesses
    double max_linear_speed = 6.0;      // m/s (12 nœuds)
    double max_angular_speed = 0.785398; // rad/s (45 degrés/s)

    linear_speed = std::clamp(linear_speed, 0.0, max_linear_speed); // Pas de marche arrière
    angular_speed = std::clamp(angular_speed, -max_angular_speed, max_angular_speed);

    // Création du message de commande
    auto cmd_msg = geometry_msgs::msg::Twist();
    cmd_msg.linear.x = linear_speed;
    cmd_msg.angular.z = angular_speed;

    // Publication de la commande
    cmd_publisher_->publish(cmd_msg);

    RCLCPP_INFO(this->get_logger(), "Published Twist Command -> Linear: %.2f m/s, Angular: %.2f rad/s",
                linear_speed, angular_speed);
}

void ControlNode::checkCommandTimeout()
{
    if (!command_received_)
    {
        // Envoyer une commande nulle pour arrêter le bateau
        auto cmd_msg = geometry_msgs::msg::Twist();
        cmd_msg.linear.x = 0.0;
        cmd_msg.angular.z = 0.0;
        cmd_publisher_->publish(cmd_msg);

        RCLCPP_WARN(this->get_logger(), "No odometry received within timeout. Stopping the boat.");
        goal_received_ = false; // Arrêter le suivi de trajectoire
    }
    else
    {
        command_received_ = false; // Réinitialiser pour la prochaine vérification
    }
}

int main(int argc, char * argv[])
{
    rclcpp::init(argc, argv);
    auto node = std::make_shared<ControlNode>();
    rclcpp::spin(node);
    rclcpp::shutdown();
    return 0;
}
